apiRules:
- include:
    uidRegex: ^Configuration
    type: Namespace
- include:
    uidRegex: ^RigidBody
    type: Namespace
- include:
    uidRegex: ^SoftBody
    type: Namespace
- include:
    uidRegex: ^Tests
    type: Namespace
- include:
    uidRegex: ^Utility
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace